# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: schedule-postgres
    environment:
      POSTGRES_DB: schedule_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Опционально: раскомментируй init.sql, если он нужен
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: