spring.application.name=diplom_project_2

# Server
server.port=8080

# Database (??????????? ?? Docker-???? 5433)
spring.datasource.url=jdbc:postgresql://localhost:5433/schedule_db
spring.datasource.username=postgres
spring.datasource.password=123

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

# Flyway
spring.flyway.enabled=true